/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoja1algoritmosprogramaradio;

import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author SDiego
 */
public class GUIRadio extends javax.swing.JFrame {
    private final Radio radio;

    /**
     * Creates new form GUIRadio
     */
    public GUIRadio() {
        initComponents();
        
        radio = new Radio();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        bnext = new javax.swing.JButton();
        bprev = new javax.swing.JButton();
        bguardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bFM = new javax.swing.JRadioButton();
        bAM = new javax.swing.JRadioButton();
        onoff = new javax.swing.JCheckBox();
        texto = new javax.swing.JTextField();
        cboxcanal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b10.setText("b10");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b11.setText("b11");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b12.setText("b12");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });

        b1.setText("b1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("b2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("b3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        b4.setText("b4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });

        b5.setText("b5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setText("b6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setText("b7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        b8.setText("b8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });

        b9.setText("b9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        bnext.setText("Next.");
        bnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnextActionPerformed(evt);
            }
        });

        bprev.setText("Prev.");
        bprev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bprevActionPerformed(evt);
            }
        });

        bguardar.setText("Guardar");
        bguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguardarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("FM UVG AM");

        buttonGroup1.add(bFM);
        bFM.setSelected(true);
        bFM.setText("FM");
        bFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFMActionPerformed(evt);
            }
        });

        buttonGroup1.add(bAM);
        bAM.setText("AM");
        bAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAMActionPerformed(evt);
            }
        });

        onoff.setSelected(true);
        onoff.setText("ON/OFF");
        onoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onoffActionPerformed(evt);
            }
        });

        texto.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        texto.setText("87.9");

        cboxcanal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));

        jLabel2.setText("Elija el canal en donde desea guardar la estacion presente:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bFM)
                        .addGap(18, 18, 18)
                        .addComponent(bAM)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bnext))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bprev)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(b1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(b7))
                            .addComponent(bguardar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(b12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(onoff))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(320, 320, 320)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cboxcanal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(325, 325, 325)
                                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 4, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboxcanal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFM)
                    .addComponent(bAM))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bnext)
                    .addComponent(bprev))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1)
                    .addComponent(b2)
                    .addComponent(b3)
                    .addComponent(b4)
                    .addComponent(b5)
                    .addComponent(b6)
                    .addComponent(b7)
                    .addComponent(b8)
                    .addComponent(b9)
                    .addComponent(b10)
                    .addComponent(b11)
                    .addComponent(b12))
                .addGap(18, 18, 18)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(onoff)
                    .addComponent(bguardar))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(0);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(0);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
         if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(1);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(1);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(2);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(2);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(3);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(3);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(4);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(4);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(5);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(5);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(6);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(6);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(7);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(7);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(8);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(8);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(9);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(9);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(10);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(10);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b11ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            float fav = radio.SeleccionarFav(11);
            texto.setText(String.format("%.1f", fav));
        }else{
            float fav = radio.SeleccionarFav(11);
            texto.setText(String.format("%.1f", fav));
        }
        System.out.println(Arrays.toString(radio.getFav()));
    }//GEN-LAST:event_b12ActionPerformed

    private void bFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFMActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            radio.Switch(false);
        }
        texto.setText("87.9"); 
    }//GEN-LAST:event_bFMActionPerformed

    private void bAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAMActionPerformed
        // TODO add your handling code here:
        if(bAM.isSelected()==true){
            radio.Switch(true);
        }
        texto.setText("530.0");
    }//GEN-LAST:event_bAMActionPerformed

    private void onoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onoffActionPerformed
        // TODO add your handling code here:
        if(onoff.isSelected()==true){            
            b1.setEnabled(true);b2.setEnabled(true);b3.setEnabled(true);b4.setEnabled(true);
            b5.setEnabled(true);b6.setEnabled(true);b7.setEnabled(true);b8.setEnabled(true);
            b9.setEnabled(true);b10.setEnabled(true);b11.setEnabled(true);b12.setEnabled(true);
            bprev.setEnabled(true);bnext.setEnabled(true);bguardar.setEnabled(true); 
        }else if(onoff.isSelected()==false){ 
            b1.setEnabled(false);b2.setEnabled(false);b3.setEnabled(false);b4.setEnabled(false);
            b5.setEnabled(false);b6.setEnabled(false);b7.setEnabled(false);b8.setEnabled(false);
            b9.setEnabled(false);b10.setEnabled(false);b11.setEnabled(false);b12.setEnabled(false);
            bprev.setEnabled(false);bnext.setEnabled(false);bguardar.setEnabled(false);
        }
    }//GEN-LAST:event_onoffActionPerformed

    private void bprevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bprevActionPerformed
        // TODO add your handling code here:
        String numstr = texto.getText();
        float num = Float.parseFloat(numstr);
        if(bFM.isSelected()==true){
            if(num>87.9 && num<107.9){
                radio.anterior(num);
                float freq = radio.anterior(num);
                String freqstr = Float.toString(freq);
                texto.setText(String.format("%.1f", freq));
                //texto.setText(freqstr);
            }else{
                JOptionPane.showMessageDialog(null, "La emisora FM tiene de rango (87.9-107.9)","Fuera de rango",JOptionPane.INFORMATION_MESSAGE);
            }
        }else if(bAM.isSelected()==true){
            if(num>530.0 && num<1610.0){
                radio.anterior(num);
                float freq = radio.anterior(num);
                String freqstr = Float.toString(freq);
                texto.setText(String.format("%.1f", freq));
                //texto.setText(freqstr);
            }else{
                JOptionPane.showMessageDialog(null, "La emisora AM tiene de rango (530-1610)","Fuera de rango",JOptionPane.INFORMATION_MESSAGE);
            }
        } 
    }//GEN-LAST:event_bprevActionPerformed

    private void bnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnextActionPerformed
        // TODO add your handling code here:
        String numstr = texto.getText();
        float num = Float.parseFloat(numstr);
        if(bFM.isSelected()==true){
            if(num>87.9 && num<107.9){
                radio.siguiente(num);
                float freq = radio.siguiente(num);
                String freqstr = Float.toString(freq);
                texto.setText(String.format("%.1f", freq));
                //texto.setText(freqstr);
            }else{
                JOptionPane.showMessageDialog(null, "La emisora FM tiene de rango (87.9-107.9)","Fuera de rango",JOptionPane.INFORMATION_MESSAGE);
            }
        }else if(bAM.isSelected()==true){
            if(num>530.0 && num<1610.0){
                radio.siguiente(num);
                float freq = radio.siguiente(num);
                String freqstr = Float.toString(freq);
                texto.setText(String.format("%.1f", freq));
                //texto.setText(freqstr);
            }else{
                JOptionPane.showMessageDialog(null, "La emisora AM tiene de rango (530-1610)","Fuera de rango",JOptionPane.INFORMATION_MESSAGE);
            }
        }        
    }//GEN-LAST:event_bnextActionPerformed

    private void bguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguardarActionPerformed
        // TODO add your handling code here:
        if(bFM.isSelected()==true){
            String canalstr = cboxcanal.getSelectedItem().toString();
            int canal = Integer.parseInt(canalstr);
            String freqstr = texto.getText();float freq = Float.parseFloat(freqstr);
            radio.guardar(freq, canal);
            JOptionPane.showMessageDialog(null, "La frecuencia "+String.format("%.1f", freq)+" "
                + "se ha guardado en el canal "+canal,"Frecuancia guardada",JOptionPane.INFORMATION_MESSAGE);
        }else if(bAM.isSelected()==true){
            String canalstr = cboxcanal.getSelectedItem().toString();
            int canal = Integer.parseInt(canalstr);
            String freqstr = texto.getText();float freq = Float.parseFloat(freqstr);
            radio.guardar(freq, canal);
            JOptionPane.showMessageDialog(null, "La frecuencia "+String.format("%.1f", freq)+" "
                + "se ha guardado en el canal "+canal,"Frecuancia guardada",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_bguardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRadio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRadio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JRadioButton bAM;
    private javax.swing.JRadioButton bFM;
    private javax.swing.JButton bguardar;
    private javax.swing.JButton bnext;
    private javax.swing.JButton bprev;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboxcanal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox onoff;
    private javax.swing.JTextField texto;
    // End of variables declaration//GEN-END:variables
}
